export { Homepage } from "./Home/Homepage";
export { ProductList } from "./Product/ProductList";
export { ProductDetails } from "./ProductDetails";
export { Login } from "./Login";
export { Register } from "./Register";
export { CartPage } from "./Cart/CartPage";
export { OrderPage } from "./Order/OrderPage";
export { DashboardPage } from "./Dashboard/DashboardPage";
export { PageNotFound } from "./PageNotFound";
